/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HealthRecordService } from "../healthRecord.service";
import { HealthRecordCreateInput } from "./HealthRecordCreateInput";
import { HealthRecord } from "./HealthRecord";
import { HealthRecordFindManyArgs } from "./HealthRecordFindManyArgs";
import { HealthRecordWhereUniqueInput } from "./HealthRecordWhereUniqueInput";
import { HealthRecordUpdateInput } from "./HealthRecordUpdateInput";

export class HealthRecordControllerBase {
  constructor(protected readonly service: HealthRecordService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HealthRecord })
  async createHealthRecord(
    @common.Body() data: HealthRecordCreateInput
  ): Promise<HealthRecord> {
    return await this.service.createHealthRecord({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [HealthRecord] })
  @ApiNestedQuery(HealthRecordFindManyArgs)
  async healthRecords(@common.Req() request: Request): Promise<HealthRecord[]> {
    const args = plainToClass(HealthRecordFindManyArgs, request.query);
    return this.service.healthRecords({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HealthRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async healthRecord(
    @common.Param() params: HealthRecordWhereUniqueInput
  ): Promise<HealthRecord | null> {
    const result = await this.service.healthRecord({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HealthRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateHealthRecord(
    @common.Param() params: HealthRecordWhereUniqueInput,
    @common.Body() data: HealthRecordUpdateInput
  ): Promise<HealthRecord | null> {
    try {
      return await this.service.updateHealthRecord({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HealthRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteHealthRecord(
    @common.Param() params: HealthRecordWhereUniqueInput
  ): Promise<HealthRecord | null> {
    try {
      return await this.service.deleteHealthRecord({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
